doc.type.html
script
this.img=document.createelement(covid)
img.src=http://www.google.com/intl/en_com/images/logo_plain.png
src=document getelementbyid(header)
src.appendchild(this.img)
filename=covidstrings23.js
java.awt graphics 
div id=header></div>
audio=new audio(audio_file mp3)
audio.play 
random button
new button (set random color)
option button
new  button(change color)
public fun with graphics(){
color panel=new j panel();
add (panel,center )
button panel
new panel (flowlayout.center)
buttonpanel.add(randombutton);
random.button add actionlistener(new action listener)
override 
public actionperformed(actionevent e)
random r= newrandom();
colorpanel.setbackground(new color (rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),(rnextint(13),(rnextint(13),(rnextint(13),(rnextint(13),(rnextint(13)))
num teams
total players=players per team
if players per team=zero
return zero
else 
return math floor total players/players per team
teamsgrouping=(rnextint8)(rnextint8)(rnextint8)(rnextint8)(rnextint8)(rnextint8)(rnextint8)
buttonpanel.add(optionbutton);
optionbutton.add actionlistener(new action listener)
override 
public actionperformed(actionevent e)
colorm=jcolorchooser.showdialog(funwithgraphics.this)
if(multi!=null)
color panel set.background(multi)
this.add(buttonpanel,borderlayout.south)
public static main(string [] args)
jframef =new covid strings23()
f.set title(covid strings23)
f.set default closeoperation(exit_on_close);
f.setsize
f.set visible(true);
<label id=lblscore>zero</label>
score=zero
if (mult == x*y)
[non-concatenated]
score+=ten
else:
score-=ten
if (mult ==x*y)
[concatenated]
score+=twenty
else:
score-=twenty
lblscore=document.getelementbyid(lblscore)
lbl.score.innerHTML=score
public actionperformed(action event e) 
system.out print.in (next button clicked)
frame.add(next button);
frame set visible true
object{a:one,b:two,c:three,d:four,e:five,f:six,g:seven,h:eight}
keys object keys(team)
entries object entries(obj);
value object=[team color]
covidstrings teamlist23= [yellow moxie,burgundy rebuilders,blue curve crushers,green peacemakers,orange rna messengers,purple brave hearts,indigo isos,red protein spikers]
covid strings multiple choice list23=[1:a2019 b2015 c2020 d1690,2:a saturday b on presidents day c parties d hangovers,3:a flu b rsv c the common cold d january6th defendants ,4:a65 b55 c217 d4 thousand,5:a watching bridgerton b loneliness c suicides d raves,6:a2nd b3rd c4th d5th,7:a mental b physical c faraday futures d child stars,8:a rad b much like animal house c bad d much like hearing ryan seacrest host wheel of fortune,9:a younger b teen wolves c older d pro-athletes,10:a worse b the same c milder d into your head,11:a five b eight tenths c three d two,12:a9 b24 c16 d45,13:a world war1 casualties b48 hours is on c restrictions d the new car smell,14:a7 b33 c5 d55 15: a november b march c december d jocktober,16:a cdc b the ochos c nathans hot dog eating contest d nih,17:a2045 b1918 c2075 d2020,18:a ups b post c budget and management d cnn]
covidstringsphraselist23=[non-concatenated strings "covid may have actually killed off a strain of flu"
"this comes on top of the fact that covid restrictions have stopped flu from spreading in2020"
"not surprisingly flu could tick up when restrictions are lifted"
"covid may not have just impacted mental health but long covid may have a side effect of insomnia"
"this on top of the fact that covid already has caused an epidemic of loneliness" 
"new cdc guidelines on isolation include ending it if an individual has been fever free for24 hours"
"if that sounds concerning recommendations still say that people should take additional precautions for at least the next5 days"
"the bad news is that  post office  will stop accepting orders for free covid tests on march8th"
concatenated strings
"one"+"reminder"+"of"+"getting"+"vaccinated"+"is"+"probably"+"dont"+"try"+"and"+"get"+"217"+"jabs"
"it"+"is"+"also"+"important"+"to"+"know"+"that"+"older"+"people"+"should"+"specifically"+"get"+"their"+"2nd"+"shot"+"in"+"the"+"spring"
"long"+"covid"+"can"+"also"+"lead"+"to"+"hangovers"+"that"+"are"+"pretty"+"bad"
"covid"+"hangovers"+"are"+"miles"+"worse"+"than"+"super"+"bowl"+"hangovers"
"for"+"example"+"younger"+"people"+"are"+"more"+"likely"+"to"+"die"+"of"+"a"+"heart"+"attack"+"post"+"covid"
"even"+"so"+"covid"+"as"+"a"+"whole"+"has"+"gotten"+"milder"
"one"+"in"+"three"+"adults"+"though"+"develop"+"some"+"sort"+"of"+"medical"+"condition"]
covid strings math problemslist23=[ non-concatenated "if a graph shows a decreasing line of flu infections in2020 compared to an increasing number of covid infections what is the relationship"?,"if the slope of the graph of covid and flu infections is2 and the y intercept is3 find the y coordinate if the x coordinate is(4,11)"?
,"if the point of (4,11) was reflected along the y axis what would the new point be"?,"if the covid point of (-4,11) was rotated270 degrees counterclockwise what would the resulting point be"?,"if the slope of the line with the flu in2020 was zero would it ever intersect with covid"?,
concatenated "if"+"a"+"poll"+"showed"+"80"+"percent"+"of"+"americans"+"were"+"surprised"+"that"+"covid"+"killed"+"off"+"a"+"strain"+"of"+"flu"+"what"+"percent"+"dont"?,"if"+"70"+"percent"+"were"+"mildly"+"surprised"+"what"+"percent"+"was"+"strong"?,"if"+"the"+"margin"+"of"+"error"+"is"+"10.2"+"percent"+"what"+"is"+"the"+"range"?,"if"+"a"+"poll"+"shows"+"62"+"percent"+"are"+"concerned"+"about"+"the"+"cdc"+"dropping"+"its"+"5"+"day"+"isolation"+"recommendation"+"what"+"percent"+"dont"?,"if"+"44"+"percent"+"are"+"strongly"+"concerned"+"what"+"percent"+"is"+"mild"?,"if"+"the"+"margin"+"of"+"error"+"is"+"5.25"+"percent"+"what"+"is"+"the"+"range"?]
covid strings sentence list23=["one should not worry about cdc isolation guidelines easing up","it should be a historical fact that covid killed the flu in2020","the post office stopping delivering covid tests is reprehensible"]
covid strings scrambled phraselist23=["0202"+"ovcid"+"luf","42roush"+"evfer"+"refe","ditational"+"careputinos"+"5yads"]
userin.select team
import meta.
class myclass
constructor(non-concatenated)
return category
if category==math problem:
prompt
log
else:
select from multiple choice
if problem=multiple choice 
select from multiple choice
else
prompt 
log
myclass=new.myclass(concatenated)
return category
if category==math problem:
prompt
log
else:
select from multiple choice
if problem=multiple choice 
select from multiple choice
else
prompt 
log
import syntax
chart js 
def gradient
id=mygradient
gradientunits=userspaceonuse
x1=0
y1=3
x2=4
y2=x2(2)+y1
stop offset=0 stop-color=ff0000
stop offset=1 stop color=0000ff
a<lineargradient>
<filter
id=linear1
filterunits=objectboundingbox
x=0%
y=0%
width=100%
height=100%
<fecomponenttransfer>
<fefunccovidstrings type=linear slope>=1
function1=effect of covid infections on flu infections
if function1slope<0:
return inverse relationship
else:
return no or direct relationship
transformationlist=[reflection,rotation,translation]
if reflection(4,11)==y axis:
shift y axis
else:
shift x axis
if rotation(-4,11)==270 degrees counter-clockwise:
shift270 degrees-counterclockwise
else:
shift clockwise
if seelectedanswer=correct:
return true
else:
return false
if selectedanswer=not correct
return false
else 
return true
answer checker
scanner=new scanner(system.in)
string correct answer
string useranswer=scanner.nextline()
if useranswer.equals(correctanswer)
system.out.print.in(correct)
else:
system.out.printin(incorrect)
scanner.close
check winner:
if winner==true:
log(the winner is)
if winner==false:
log(no winner yet)
if users team wins covid strings23 
console log users team wins covid strings23
else
return game over
return filename


