doc.type.html
script
filename=covid strings 23 key words.js
covid strings23 key word list=[covid restrictions stop flu,hangovers,one reminder of getting vaccinated,covid already caused,older people get shot in spring,long covid insomnia,long covid hangovers,heart attack post covid,covid as a whole,flu ticks up,recommend additional precautions,post office stops accepting orders,isolation guidelines easing up]
string=””
for string in covid strings search word list
select characters
edit diffuse property
desired color=green
covid strings23 reference list=[a:how coronavirus lockdowns stopped flu in its tracks (nature.com),b:long covid linked to alcohol sensitivity and debilitating hangovers (msn.com),c:is the super bowl hangover real or a myth? history of past losers,d:stats & records the next season|sporting news,e:the covid-19 pandemic killed off one strain of the flu,and that will change the next vaccines(msn.com),f:hyper vaccinated man reportedly received 217 covid jabs without side-effects |vaccines and immunisation |the guardian,g:covid-19 pandemic led to increase in loneliness around the world (apa.org),h:cdc recommends spring covid booster for older adults (nbcnews.com),
i:understanding sleep problems and long covid |nih covid-19 research,j:long covid could be linked to harsher hangover symptoms,study finds (msn.com),k:since covid,more young people are dying of heart attacks.heres what we know (today.com),l:covid symptoms are now more mild and follow a pattern,doctors say (nbcnews.com),m:why easing covid restrictions could prompt a fierce flu rebound (nature.com),n:the cdc has released new covid-19 guidelines around isolation heres what to know (msn.com),o:usps will stop accepting orders for free covid tests on march 8 (msn.com),p:cdc drops 5-day isolation guidance for covid-19, moving away from key strategy to quell infections|cnn]
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
a=pc.create script(a);
a.attributes.add(foobar,{type:entity});
a.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
b=pc.create script(b);
b.attributes.add(foobar,{type:entity});
b.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
c=pc.create script(c);
c.attributes.add(foobar,{type:entity});
c.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
d=pc.create script(d);
d.attributes.add(foobar,{type:entity});
d.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
e=pc.create script(e);
e.attributes.add(foobar,{type:entity});
e.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
f=pc.create script(f);
f.attributes.add(foobar,{type:entity});
f.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
g=pc.create script(g);
g.attributes.add(foobar,{type:entity});
g.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
h=pc.create script(h);
h.attributes.add(foobar,{type:entity});
h.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
i=pc.create script(i);
i.attributes.add(foobar,{type:entity});
i.prototype.initialize =function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
j=pc.create script(j);
j.attributes.add(foobar,{type:entity});
j.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
k=pc.create script(k);
k.attributes.add(foobar,{type:entity});
k.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
l=pc.create script(l);
l.attributes.add(foobar,{type:entity});
l.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
m=pc.create script(m);
m.attributes.add(foobar,{type:entity});
m.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
n=pc.create script(n);
n.attributes.add(foobar,{type:entity});
n.prototype.initialize=function()
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
o=pc.create script(o);
o.attributes.add(foobar,{type:entity});
o.prototype.initialize=function()
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
p=pc.create script(p);
p.attributes.add(foobar,{type:entity});
p.prototype.initialize=function() 
console.log(this.foobar.name);
return filename
